export enum propertyValues {
    prop_1 = 'map_tier',
    prop_2 = 'map_iiq',
    prop_3 = 'map_iir',
    prop_4 = 'map_packsize',
    prop_5 = 'gem_level',
    prop_6 = 'quality',
    prop_9 = 'pdps',
    prop_10 = 'edps',
    prop_11 = 'pseudo.pseudo_adds_chaos_damage_to_attacks',
    prop_12 = 'crit',
    prop_13 = 'aps',
    prop_15 = 'block',
    prop_16 = 'ar',
    prop_17 = 'ev',
    prop_18 = 'es',
    prop_20 = 'gem_level_progress',
    prop_32 = 'stack_size',
  }